name: PHP CI/CD with Lightweight IaC

on:
  push:
    branches: [main]

jobs:
  php-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml

      - name: Lint PHP files
        run: find cmp214/ -type f -name "*.php" -exec php -l {} \;

      - name: Install PHPUnit manually
        run: |
          wget https://phar.phpunit.de/phpunit.phar
          chmod +x phpunit.phar
          sudo mv phpunit.phar /usr/local/bin/phpunit

      - name: Run Unit Tests
        run: |
          if [ -f phpunit.xml ]; then
            phpunit
          else
            echo "No phpunit.xml config found. Skipping tests."
          fi


  deploy:
    runs-on: ubuntu-latest
    needs: php-ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run setup scripts (IaC-like step)
        run: |
          if [ -f setup/permissions.sh ]; then
            bash setup/permissions.sh
          fi

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/

          
  

