name: PHP CI/CD with Lightweight IaC

on:
  pull_request:
    branches: [main]  # Trigger when PR is made to 'main'

jobs:
  php-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml

      - name: Lint PHP files
        run: find cmp214/ -type f -name "*.php" -exec php -l {} \;

      - name: Run Unit Tests (if any)
        run: |
          if [ -f tests/run-tests.sh ]; then
            bash tests/run-tests.sh
          else
            echo "No test script found."
          fi

  merge-pr:
    runs-on: ubuntu-latest
    needs: php-ci
    steps:
      - name: Install GitHub CLI
        run: |
          curl -s https://cli.github.com/install.sh | bash

      - name: Merge PR if tests pass
        if: success() && github.event.pull_request.head.ref != 'main'
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin

  deploy:
    runs-on: ubuntu-latest
    needs: merge-pr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run setup scripts (IaC-like step)
        run: |
          if [ -f setup/permissions.sh ]; then
            bash setup/permissions.sh
          fi

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
     
  

